spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chirpDB?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: false
    hibernate.ddl-auto: validate

    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
