spring:
  profiles:
    default: local
    group:
      local: server,security,datasource,jpa,cors,jwt,h2db,email,emailsecurity
      prod: server,security,datasource,jpa,cors,jwt,mysql,email,emailsecurity
